config/routes.rb
Breadcrumb::Application.routes.draw do
  resources :tutorials

  resources :providers

  devise_for :users
  get "static_pages/index"
  get "static_pages/about"
  get "static_pages/help"

  root 'static_pages#index'

end

app/models/provider.rb
class Provider
  include Mongoid::Document
  field :url, type: String
  field :name, type: String
  field :description, type: String
  field :img, type: String

  has_many :tutorials
end

app/models/tutorial.rb
class Tutorial
  include Mongoid::Document
  field :url, type: String
  field :name, type: String
  field :description, type: String
  # field :provider_id, type: ObjectId


  belongs_to :provider
  validates_uniqueness_of :url
  validates_presence_of :name, :provider_id
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## User profile
  field :first_name,         :type => String
  field :last_name,          :type => String
  field :dream_job,          :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name 
    devise_parameter_sanitizer.for(:sign_up) << :last_name
    devise_parameter_sanitizer.for(:sign_up) << :dream_job 
  end

end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  def index
    @providers = Provider.all
  end

  def show
    @provider = Provider.find(params[:id])
  end

  def new
    @provider = Provider.new
  end

  def create
    provider = Provider.create(provider_params)
    provider.save
    redirect_to providers_path
  end

  protected

  def provider_params
    params.required(:provider).permit(:name, :description, :url, :img)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
  end

  def help
  end
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  def new
    @tutorial = Tutorial.new
  end

  def edit
    @tutorial = Tutorial.find(params[:id])
  end
  
  def index
    @tutorials = Tutorial.all
  end

  def show
    @tutorial = Tutorial.find(params[:id])
  end

  def create
    @tutorial = Tutorial.new(tutorial_params)
    if @tutorial.save
      redirect_to tutorials_path
    else
      render :new
    end
  end

  def destroy
    @tutorial = Tutorial.find(params[:id])
    @tutorial.delete
    redirect_to tutorials_path
  end

  private

  def tutorial_params
    params.required(:tutorial).permit(:name, :description, :url, :provider_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def create
    User.create(sign_up_params)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-danger"
      when :alert then "alert alert-warning"
    end
  end
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Breadcrumb", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", static_pages_about_path %></li>
        <li><%= link_to "Help", static_pages_help_path %></li>
        <% if current_user %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Breadcrumb</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/navbar" %>
  <div class="container">
    <div class="row">
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= value %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </div>
  

</body>
</html>

app/views/providers/index.html.erb
<div class="col-sm-12">
  
  <h2>Content Providers</h2>
  <br>
</div>

<ul class="list-unstyled">
  <% @providers.each do |provider| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= image_tag provider.img %>
        <div class="caption">
          <h3><%= link_to provider.name, provider.url %></h3>
          <p><%= provider.description %></p>
          
        </div>
        <div class="actions">
          <p><%= link_to "View lessons", provider_path(provider), class: "btn btn-primary" %> <a href="#" class="btn btn-default" role="button">Button</a></p>
        </div>
      </div>
    </div>
    <!-- <li>
      <%= image_tag provider.img %>
      <h4><%= link_to provider.name, provider.url %></h4>
      <p><%= provider.description %></p>
    </li> -->
  <% end %>
</ul>

app/views/providers/new.html.erb
<div class="col-sm-8">
  <div class="col-sm-8 col-sm-offset-4">
    <h2>Add a new content provider</h2>
  </div>

  <%= form_for( @provider, html: {class: "form-horizontal", role: "form"}) do |f| %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-4 control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :name, class: "form-control", autofocus: true %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: "col-sm-4 control-label" %>
    <div class="col-sm-8">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :url, class: "col-sm-4 control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :url, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :img, class: "col-sm-4 control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :img, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-8 col-sm-offset-4">
      <%= f.submit "Save", class: "btn btn-primary" %>
    </div>
  </div>

  <% end %>
  
</div>

app/views/providers/show.html.erb
<h2><%= @provider.name %></h2>

<% @provider.tutorials.each do |tutorial| %>
  <h4><%= tutorial.name %></h4>
  <%= link_to "View", tutorial_path(tutorial), class: "btn btn-default" %>
  <%= link_to "Edit", edit_tutorial_path(tutorial), class: "btn btn-default" %>

<% end %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/index.html.erb
<div class="jumbotron">
  <h1>Welcome to Breadcrumb.io</h1>
  <p>The easiest way to find the best open learning resources</p>
  <p><a class="btn btn-primary btn-lg" role="button">Get started</a></p>
</div>

app/views/tutorials/_form.html.erb
<%= form_for( @tutorial, html: {class: "form-horizontal", role: "form"}) do |f| %>
  <% if @tutorial.errors.any? %>
    <div class="col-sm-8 col-sm-offset-4">
      <p><%= pluralize(@tutorial.errors.count, "error") %> prohibited this tutorial from being saved:</p>
      <ul>
        <% @tutorial.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
    </ul>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-4 control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :name, class: "form-control", autofocus: true %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: "col-sm-4 control-label" %>
    <div class="col-sm-8">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :url, class: "col-sm-4 control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :url, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :provider_id, class: "col-sm-4 control-label" %>
    <div class="col-sm-8">
      <%= f.collection_select :provider_id, Provider.all, :id, :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-8 col-sm-offset-4">
      <%= f.submit "Save", class: "btn btn-primary" %>
    </div>
  </div>

  <% end %>

app/views/tutorials/edit.html.erb
<div class="col-sm-8">
  <div class="col-sm-8 col-sm-offset-4">
    <h2>Edit tutorial</h2>
  </div>

  <%= render "form" %>
</div>

app/views/tutorials/index.html.erb
<h2>All tutorials</h2>

<% @tutorials.each do |tutorial| %>
  <h4><%= tutorial.name %></h4>
<% end %>

app/views/tutorials/new.html.erb
<div class="col-sm-8">
  <div class="col-sm-8 col-sm-offset-4">
    <h2>Add a new tutorial</h2>
  </div>

  <%= render "form" %>
</div>

app/views/tutorials/show.html.erb
<h2><%= @tutorial.name %></h2>
<%= link_to "delete", tutorial_path(@tutorial), method: :delete %>